substitutions:
  _SERVICE: "varzea-pro-scout"
  _REGION: "us-central1"
  _REPO: "varzea-pro-scout"

steps:
  # Install deps and build
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - -lc
      - |
        npm ci
        npm run build

  # Build Docker image and push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_REPO:$SHORT_SHA', '.']

images:
  - 'gcr.io/$PROJECT_ID/$_REPO:$SHORT_SHA'

  # Deploy to Cloud Run using the built image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - -lc
      - |
        gcloud --quiet run deploy ${_SERVICE} \
          --image=gcr.io/$PROJECT_ID/$_REPO:$SHORT_SHA \
          --platform=managed \
          --region=${_REGION} \
          --allow-unauthenticated

timeout: '1200s'
