substitutions:
  _SERVICE: "varzea-pro-scout"
  _REGION: "us-west1"
  _REPO: "fat-bipe"

# When a custom service account is used by the trigger, Cloud Build requires
# an explicit logs behavior or a logs bucket. Setting logging to
# CLOUD_LOGGING_ONLY ensures builds use Cloud Logging and avoids the
# 'build.logs_bucket' validation error.
options:
  logging: CLOUD_LOGGING_ONLY
  # When a custom service account is used by the trigger, Cloud Build
  # may require an explicit logs-bucket behavior. Setting
  # `default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET` is a
  # compatible option that avoids the validation error when a
  # `build.service_account` is present on the trigger.
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

steps:
  # Install deps and build
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - -lc
      - |
        npm ci
        npm run build

  # Build Docker image and push to Container Registry (compute a TAG fallback)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-lc', 'if [ -z "$SHORT_SHA" ]; then TAG=manual; else TAG=$SHORT_SHA; fi; echo "Using TAG=$$TAG"; docker build -t gcr.io/$PROJECT_ID/$_REPO:$$TAG .; docker push gcr.io/$PROJECT_ID/$_REPO:$$TAG']

  # Deploy to Cloud Run using the built image (use same TAG fallback)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    env:
      - 'PROJECT_ID=$PROJECT_ID'
    # Call the repository script which sanitizes/ignores extra args appended by the runner
    args: ['-lc', 'bash ./scripts/deploy-cloudrun.sh']

timeout: '1200s'
