substitutions:
  _SERVICE: "varzea-pro-scout"
  _REGION: "us-west1"
  _REPO: "fat-bipe"

steps:
  # Install deps and build
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - -lc
      - |
        npm ci
        npm run build

  # Build Docker image and push to Container Registry (compute a TAG fallback)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -lc
      - |
        if [ -z "$SHORT_SHA" ]; then
          TAG=manual
        else
          TAG=$SHORT_SHA
        fi
        echo "Using TAG=$TAG"
        docker build -t gcr.io/$PROJECT_ID/$_REPO:$TAG .
        docker push gcr.io/$PROJECT_ID/$_REPO:$TAG

  # Deploy to Cloud Run using the built image (use same TAG fallback)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - -lc
      - |
        if [ -z "$SHORT_SHA" ]; then
          TAG=manual
        else
          TAG=$SHORT_SHA
        fi
        gcloud --quiet run deploy ${_SERVICE} \
          --image=gcr.io/$PROJECT_ID/$_REPO:$TAG \
          --platform=managed \
          --region=${_REGION} \
          --allow-unauthenticated

timeout: '1200s'
